services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_NAME=flightclub
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:6
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
